### ISSUE TITLE
Multiple Issues After Changing Vote: Missing Secret Phrase, No "Success" Modal

### ISSUE THREAD

**Issue by myoung** [joincivil/Civil#725] opened 2019-01-03 18:54 UTC
After changing my vote (from rejected to approved), the “secret phrase” is missing. When clicking “confirm with metamask” button, MM pops up very quickly and then disappears. No error message. Nothing in the JS console. My initial CVL token voting amount was “111” and in this case it was less “59.xxx”. If you do change the vote and do an amount greater than the initial amount, the MM transaction will work but you never get the “Success!” Modal even though the MM transaction succeeded. It’s unclear if the vote actually changed.

![image](https://user-images.githubusercontent.com/187748/50655692-e7b12700-0f5e-11e9-9076-044a845bbe5f.png)

**Comment by am9u** [comment] 2019-01-11 15:20
I believe this was caused by the same underlying issue behind #726, but will verify with some testing.

**Comment by am9u** [comment] 2019-01-16 16:43
I tested this at it seems to be resolved, so I'm closing this issue. 

If it comes up again, we can re-open.

**Closed by am9u** 2019-01-16 16:43 UTC
Labels: Cost: .5, P1, bug, dapp
